### ISSUE TITLE
Update to new badges?

### ISSUE THREAD

**Issue by julia-r** [steverichey/google-play-badge-svg#1]
Hello,

nice Project! But in the meantime Google has updated the badges and they use a different font on it now. Are you going to update the SVGs? 

https://play.google.com/intl/en_us/badges/

**Comment by steverichey** [comment]
Good call! I can't promise anything but if I can find time I'll certainly take care of this.

**Comment by steverichey** [comment]
Done! Thanks for bringing this to my attention.
